FROM ubuntu:latest@sha256:5747316366b8cc9e3021cd7286f42b2d6d81e3d743e2ab571f55bcd5df788cc8
LABEL maintainer="chrisns"

RUN apt-get update && \
    apt-get install -y \
    make \
    g++

WORKDIR /openzwave
COPY open-zwave .
RUN make install