FROM debian:10.4@sha256:18f374fa88f9230a5c860f986dc83d3d03a056708164ff30c98d0e789e90946d
LABEL maintainer="chrisns"

RUN apt-get update && \
    apt-get install -y \
    make \
    g++

WORKDIR /openzwave
COPY open-zwave .
RUN make install