FROM centos:8@sha256:9e0c275e0bcb495773b10a18e499985d782810e47b4fce076422acb4bc3da3dd
LABEL maintainer="chrisns"

RUN yum install -y \
  make \
  gcc-c++

WORKDIR /openzwave
COPY open-zwave .
RUN make install