FROM alpine:3.13.5
LABEL maintainer="chrisns"

RUN apk --no-cache add \
    git \
    eudev-dev \
    coreutils \
    linux-headers \
    alpine-sdk \
    python3 \
    openssl

WORKDIR /openzwave
COPY open-zwave .
RUN make install
