name: Docker Build

on:
  schedule:
    - cron:  '* 0 * * *'
  push:
    branches:
      - master
  pull_request:

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      tags: ${{ steps.set-matrix.outputs.tags }}
    steps:
    - id: set-matrix
      run: |
        wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
        unzip pup_v0.4.0_linux_amd64.zip

        wget http://old.openzwave.com/downloads/ -O downloads.html
        VERSION1=$(cat downloads.html | ./pup '#pagecontent > table:nth-child(2) > tbody > tr:nth-child(2) > td:nth-child(1) text{}')
        VERSION2=$(cat downloads.html | ./pup '#pagecontent > table:nth-child(2) > tbody > tr:nth-child(3) > td:nth-child(1) text{}')
        VERSION3=$(cat downloads.html | ./pup '#pagecontent > table:nth-child(2) > tbody > tr:nth-child(4) > td:nth-child(1) text{}')
        MATRIX="{\"openzwave\":[\"git\",\"$VERSION1\",\"$VERSION2\",\"$VERSION3\"],\"dockerfile\":[\"alpine\",\"debian\",\"ubuntu\",\"centos8\"]}"
        TAGS=$(wget -q https://registry.hub.docker.com/v1/repositories/chrisns/openzwave/tags -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}')
        echo "::set-output name=matrix::$MATRIX"
        echo "::set-output name=tags::$TAGS"
  build:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}
    steps:
      - name: Set tag
        run: echo '::set-env name=BUILD_TAG::${{ matrix.dockerfile }}-${{ matrix.openzwave }}'
      - name: Check existing
        id: should
        run: echo "::set-output name=build::${{ !contains(needs.matrix.outputs.tags , env.BUILD_TAG) }}"
      - uses: actions/checkout@v2
        if: ${{ matrix.openzwave == 'git'}}
        with:
          submodules: true

      - uses: actions/checkout@v2
        if: ${{ steps.should.outputs.build == 'true' && matrix.openzwave != 'git'}}

      - name: Get and extract stable github
        if: ${{ steps.should.outputs.build == 'true' && matrix.openzwave != 'git'}}
        run: |
          curl -o ozw.tar.gz http://old.openzwave.com/downloads/openzwave-${{ matrix.openzwave }}.tar.gz
          tar -xzvf ozw.tar.gz
          rm -rf open-zwave
          mv openzwave-${{ matrix.openzwave }} open-zwave
          mkdir -p .git/modules/open-zwave/refs/heads
          echo ${{ matrix.openzwave }} > .git/modules/open-zwave/refs/heads/master

      - name: Just build linux/amd64 on PR
        if: ${{ steps.should.outputs.build == 'true' && github.event_name == 'pull_request' }}
        run: |
          docker build -f Dockerfile.${{ matrix.dockerfile }} .

      - name: Login to dockerhub
        if: ${{ steps.should.outputs.build == 'true' && github.event_name != 'pull_request' }}
        run: |
          docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - uses: crazy-max/ghaction-docker-buildx@v1
        if: ${{ steps.should.outputs.build == 'true' && github.event_name != 'pull_request' }}

      - name: build+push
        if: ${{ steps.should.outputs.build == 'true' && github.ref == 'refs/heads/master'}}
        run: |
          docker buildx build \
          -f Dockerfile.${{ matrix.dockerfile }} \
          --platform $(cat SupportedArch.${{ matrix.dockerfile }}) \
          -t chrisns/openzwave:${{ matrix.dockerfile }}-${{ matrix.openzwave }} \
          -t chrisns/openzwave:${{ matrix.dockerfile }}-sha-$(cat .git/modules/open-zwave/refs/heads/master) \
          --push \
          .
