name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile: [alpine, debian, ubuntu, centos8]

    steps:
      - uses: actions/checkout@v2

      - name: Just build linux/amd64 on PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          docker build -f Dockerfile.${{ matrix.dockerfile }} .

      - name: Login to dockerhub
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - uses: crazy-max/ghaction-docker-buildx@v1
        if: ${{ github.event_name != 'pull_request' }}

      - name: build+push
        if: ${{ github.ref == 'refs/heads/master'}}
        run: |
          docker buildx build \
          -f Dockerfile.${{ matrix.dockerfile }} \
          --platform linux/arm64/v8,linux/amd64,linux/arm/v6,linux/arm/v7,linux/386 \
          -t chrisns/openzwave:${{ matrix.dockerfile }} \
          -t chrisns/openzwave:${{ matrix.dockerfile }}-sha:$(cat .git/modules/open-zwave/refs/heads/master) \
          --push \
          .
