name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        openzwave:
          - git
          - "1.6.1210"
          - "1.6.1209"
          - "1.6.1207"
        dockerfile: [alpine, debian, ubuntu, centos8]

    steps:
      - uses: actions/checkout@v2
        if: ${{ matrix.openzwave == 'git'}}
        with:
          submodules: true

      - uses: actions/checkout@v2
        if: ${{ matrix.openzwave != 'git'}}

      - name: Get and extract stable github
        if: ${{ matrix.openzwave != 'git'}}
        run: |
          curl -o ozw.tar.gz http://old.openzwave.com/downloads/openzwave-${{ matrix.openzwave }}.tar.gz
          tar -xzvf ozw.tar.gz
          rm -rf open-zwave
          mv openzwave-${{ matrix.openzwave }} open-zwave
          mkdir -p .git/modules/open-zwave/refs/heads
          echo ${{ matrix.openzwave }} > .git/modules/open-zwave/refs/heads/master

      - name: Just build linux/amd64 on PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          docker build -f Dockerfile.${{ matrix.dockerfile }} .

      - name: Login to dockerhub
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - uses: crazy-max/ghaction-docker-buildx@v1
        if: ${{ github.event_name != 'pull_request' }}

      - name: build+push
        if: ${{ github.ref == 'refs/heads/master'}}
        run: |
          docker buildx build \
          -f Dockerfile.${{ matrix.dockerfile }} \
          --platform $(cat SupportedArch.${{ matrix.dockerfile }}) \
          -t chrisns/openzwave:${{ matrix.dockerfile }}-${{ matrix.openzwave }}\
          -t chrisns/openzwave:${{ matrix.dockerfile }}-sha-$(cat .git/modules/open-zwave/refs/heads/master) \
          --push \
          .
